# 
#    * @project_name : GOLDEN MEGA-MD
#    * @author : @goldenmega
#    * @description : GOLDEN-Md ,A Multi-functional whatsapp bot md.
#    * @version 1.0.0


 


FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/GlobalTechInfo/SUHAIL-XMD /root/SUHAIL-XMD
# RUN rm -rf /root/luv/.git
WORKDIR /root/GOLDEN MEGA-MD
RUN npm install || yarn install
EXPOSE 8000
CMD ["npm","start" ]
